-- Behavioural checks for Phase: Inbound integrations: endpoints are Admin+ only (workspace admins get no
-- bypass), tokens and signing secrets are generated by the database, shown once, and never readable;
-- a wrong, disabled, deleted, or rotated token creates nothing and gets the same generic 401; bad,
-- stale, and replayed signatures fail; an Idempotency-Key makes one task; payload mapping (section,
-- assignee, tags, fields by name) with warnings; rate limiting; the creator's access is re-checked;
-- the inbound_received rule trigger and source_is "inbound"; import / copy muting kept; and anon can
-- execute only get_public_form, submit_form, and receive_inbound_webhook.
-- Fresh people for this suite (no memberships from earlier suites):
--   f6f6…01 ib-owner@example.com     owner of IB P
--   f6f6…02 ib-admin@example.com     Admin of P (creates the endpoints)
--   f6f6…03 ib-editor@example.com    Editor of P
--   f6f6…04 ib-viewer@example.com    Viewer of P
--   f6f6…05 ib-outsider@example.com  no memberships
-- plus the workspace admin an earlier suite left (not a member of P).

\set ON_ERROR_STOP 1

create temporary table ib_ids (name text primary key, id uuid) on commit preserve rows;
create temporary table ib_vals (name text primary key, val text) on commit preserve rows;
grant all on ib_ids, ib_vals to authenticated, anon, service_role;

insert into public.allowed_emails (email, note) values
  ('ib-owner@example.com', 'inbound integrations suite'),
  ('ib-admin@example.com', 'inbound integrations suite'),
  ('ib-editor@example.com', 'inbound integrations suite'),
  ('ib-viewer@example.com', 'inbound integrations suite'),
  ('ib-outsider@example.com', 'inbound integrations suite');
insert into auth.users (id, email, email_confirmed_at, raw_user_meta_data) values
  ('f6f6f6f6-0000-4000-8000-000000000001', 'ib-owner@example.com', now(), '{"full_name":"Ola Owner"}'),
  ('f6f6f6f6-0000-4000-8000-000000000002', 'ib-admin@example.com', now(), '{"full_name":"Ada Admin"}'),
  ('f6f6f6f6-0000-4000-8000-000000000003', 'ib-editor@example.com', now(), '{"full_name":"Ed Editor"}'),
  ('f6f6f6f6-0000-4000-8000-000000000004', 'ib-viewer@example.com', now(), '{"full_name":"Vi Viewer"}'),
  ('f6f6f6f6-0000-4000-8000-000000000005', 'ib-outsider@example.com', now(), '{"full_name":"Oz Outsider"}');

insert into ib_ids values
  ('owner', 'f6f6f6f6-0000-4000-8000-000000000001'),
  ('admin', 'f6f6f6f6-0000-4000-8000-000000000002'),
  ('editor', 'f6f6f6f6-0000-4000-8000-000000000003'),
  ('viewer', 'f6f6f6f6-0000-4000-8000-000000000004'),
  ('outsider', 'f6f6f6f6-0000-4000-8000-000000000005'),
  ('ws_admin', (select profile_id from public.workspace_admins where deleted_at is null order by created_at limit 1));

-- Helpers (internal) -------------------------------------------------------------------------------

do $$
begin
  assert (select id from ib_ids where name = 'ws_admin') is not null, 'an earlier suite left a workspace admin';
  assert encode(public.inbound_hmac_sha256(convert_to('Jefe', 'UTF8'), convert_to('what do ya want for nothing?', 'UTF8')), 'hex')
    = '5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843', 'HMAC-SHA256 matches RFC 4231 test case 2';
  assert encode(public.inbound_hmac_sha256(convert_to(repeat('k', 100), 'UTF8'), convert_to('1700000000.{"a":"é"}', 'UTF8')), 'hex')
    = '640f1a37564a532fb2e28fdacc3533560344ad9cacb77bb37252f0a275322b04', 'long keys are hashed first (matches Node)';
  assert public.inbound_random_hex() ~ '^[0-9a-f]{64}$' and public.inbound_random_hex() <> public.inbound_random_hex(),
    'random hex is 64 characters and differs each time';
end $$;

-- Fixtures ----------------------------------------------------------------------------------------

set role authenticated;
select set_config('request.jwt.claim.sub', 'f6f6f6f6-0000-4000-8000-000000000001', false) is not null as ok \gset

do $$
declare
  ws uuid := '00000000-0000-4000-8000-000000000001';
  p uuid;
  other uuid;
  inbox uuid;
  doing uuid;
  other_section uuid;
  urgent uuid;
  web uuid;
  old_tag uuid;
begin
  insert into public.projects (workspace_id, name) values (ws, 'IB P') returning id into p;
  insert into public.sections (project_id, name, sort_order) values (p, 'Inbox', 1024) returning id into inbox;
  insert into public.sections (project_id, name, sort_order) values (p, 'Doing', 2048) returning id into doing;
  insert into public.projects (workspace_id, name) values (ws, 'IB Other') returning id into other;
  insert into public.sections (project_id, name, sort_order) values (other, 'Elsewhere', 1024) returning id into other_section;
  perform public.add_project_member(p, 'ib-admin@example.com', 'admin');
  perform public.add_project_member(p, 'ib-editor@example.com', 'editor');
  perform public.add_project_member(p, 'ib-viewer@example.com', 'viewer');
  insert into public.custom_fields (project_id, name, field_type, options) values
    (p, 'Priority', 'single_select', '[{"id": "hi", "name": "High", "color": "red"}, {"id": "lo", "name": "Low", "color": "zinc"}]'),
    (p, 'Budget', 'number', '[]'),
    (p, 'Launch', 'date', '[]'),
    (p, 'Reviewers', 'people', '[]');
  insert into public.tags (workspace_id, name) values (ws, 'IB Urgent') returning id into urgent;
  insert into public.tags (workspace_id, name) values (ws, 'IB Web') returning id into web;
  insert into public.tags (workspace_id, name) values (ws, 'IB Old') returning id into old_tag;
  update public.tags set archived_at = now() where id = old_tag;
  insert into ib_ids values ('p', p), ('other', other), ('inbox', inbox), ('doing', doing),
    ('other_section', other_section), ('urgent', urgent), ('web', web), ('old_tag', old_tag);
end $$;

-- Endpoint admin is Admin+ only ---------------------------------------------------------------------

do $$
declare
  p uuid := (select id from ib_ids where name = 'p');
  who text;
begin
  foreach who in array array['editor', 'viewer', 'outsider', 'ws_admin'] loop
    perform set_config('request.jwt.claim.sub', (select id::text from ib_ids where name = who), true);
    begin
      perform public.create_inbound_endpoint(p, 'Nope');
      raise exception '% should not create an endpoint', who;
    exception when insufficient_privilege then null;
    end;
    begin
      insert into public.inbound_endpoints (project_id, name) values (p, 'Direct');
      raise exception '% should not insert an endpoint directly', who;
    exception when insufficient_privilege then null;
    end;
  end loop;
end $$;

select set_config('request.jwt.claim.sub', 'f6f6f6f6-0000-4000-8000-000000000002', false) is not null as ok \gset

do $$
declare
  p uuid := (select id from ib_ids where name = 'p');
  created jsonb;
begin
  begin
    perform public.create_inbound_endpoint(p, 'Bad section', (select id from ib_ids where name = 'other_section'));
    raise exception 'a section of another project should fail';
  exception when check_violation then null;
  end;
  begin
    perform public.create_inbound_endpoint(p, 'Bad assignee', null, (select id from ib_ids where name = 'outsider'));
    raise exception 'a non-member default assignee should fail';
  exception when check_violation then null;
  end;
  begin
    perform public.create_inbound_endpoint(p, 'Archived tag', null, null, array[(select id from ib_ids where name = 'old_tag')]);
    raise exception 'archived default tags should fail';
  exception when check_violation then null;
  end;
  begin
    perform public.create_inbound_endpoint(p, '   ');
    raise exception 'a blank name should fail';
  exception when check_violation then null;
  end;

  created := public.create_inbound_endpoint(p, ' Website intake ', (select id from ib_ids where name = 'inbox'),
    (select id from ib_ids where name = 'editor'), array[(select id from ib_ids where name = 'urgent')]);
  assert created ->> 'token' ~ '^alhc_in_[0-9a-f]{64}$', format('the token is returned once, got %s', created);
  assert created ->> 'signing_secret' is null, 'no signing secret unless asked';
  insert into ib_ids values ('e1', (created ->> 'id')::uuid);
  insert into ib_vals values ('t1', created ->> 'token');

  created := public.create_inbound_endpoint(p, 'Signed', null, null, '{}', true);
  assert created ->> 'signing_secret' ~ '^whsec_[0-9a-f]{64}$', format('the signing secret is returned once, got %s', created);
  insert into ib_ids values ('e2', (created ->> 'id')::uuid);
  insert into ib_vals values ('t2', created ->> 'token'), ('s2', created ->> 'signing_secret');

  created := public.create_inbound_endpoint(p, 'Throttled');
  insert into ib_ids values ('e3', (created ->> 'id')::uuid);
  insert into ib_vals values ('t3', created ->> 'token');

  created := public.create_inbound_endpoint(p, 'Soon deleted');
  insert into ib_ids values ('e4', (created ->> 'id')::uuid);
  insert into ib_vals values ('t4', created ->> 'token');

  assert (select name from public.inbound_endpoints where id = (select id from ib_ids where name = 'e1')) = 'Website intake',
    'names are trimmed';
  assert (select token_hint from public.inbound_endpoints where id = (select id from ib_ids where name = 'e1'))
    = '…' || right((select val from ib_vals where name = 't1'), 4), 'the hint is the last 4 characters';
  assert (select created_by from public.inbound_endpoints where id = (select id from ib_ids where name = 'e1'))
    = (select id from ib_ids where name = 'admin'), 'the creator is the caller';

  begin
    perform token_hash from public.inbound_endpoints limit 1;
    raise exception 'admins should not read token hashes';
  exception when insufficient_privilege then null;
  end;
  begin
    perform signing_secret from public.inbound_endpoints limit 1;
    raise exception 'admins should not read signing secrets';
  exception when insufficient_privilege then null;
  end;
  begin
    update public.inbound_endpoints set token_hash = repeat('0', 64) where id = (select id from ib_ids where name = 'e1');
    raise exception 'admins should not write token hashes';
  exception when insufficient_privilege then null;
  end;
  begin
    update public.inbound_endpoints set signing_secret = 'whsec_chosen_by_a_person_000000' where id = (select id from ib_ids where name = 'e2');
    raise exception 'admins should not write signing secrets';
  exception when insufficient_privilege then null;
  end;
  begin
    update public.inbound_endpoints set project_id = (select id from ib_ids where name = 'other')
    where id = (select id from ib_ids where name = 'e1');
    raise exception 'endpoints should not move';
  exception when insufficient_privilege then null;
  end;
end $$;

-- Nobody below Admin (and no workspace admin) reads, rotates, or changes endpoints or the log ----------

do $$
declare
  who text;
  hits integer;
begin
  foreach who in array array['editor', 'viewer', 'outsider', 'ws_admin'] loop
    perform set_config('request.jwt.claim.sub', (select id::text from ib_ids where name = who), true);
    assert (select count(*) from public.inbound_endpoints) = 0, format('%s reads no endpoints', who);
    assert (select count(*) from public.inbound_calls) = 0, format('%s reads no calls', who);
    begin
      perform public.rotate_inbound_token((select id from ib_ids where name = 'e1'));
      raise exception '% should not rotate', who;
    exception when no_data_found then null;
    end;
    begin
      perform public.set_inbound_signing_secret((select id from ib_ids where name = 'e1'), true);
      raise exception '% should not set a signing secret', who;
    exception when no_data_found then null;
    end;
    update public.inbound_endpoints set enabled = false where id = (select id from ib_ids where name = 'e1');
    get diagnostics hits = row_count;
    assert hits = 0, format('%s changes no endpoint', who);
  end loop;
end $$;

-- Receiving as anon -----------------------------------------------------------------------------------

reset role;
set role anon;
select set_config('request.jwt.claim.sub', '', false) is not null as ok \gset

do $$
declare
  unknown jsonb;
  r jsonb;
begin
  unknown := public.receive_inbound_webhook('alhc_in_' || repeat('ab', 32), '{"title": "Guess"}');
  assert unknown = '{"ok": false, "error": "Unauthorized", "status": 401}'::jsonb, format('unknown token → generic 401, got %s', unknown);
  r := public.receive_inbound_webhook('not-a-token', '{"title": "Guess"}');
  assert r = unknown, 'malformed token → the same 401';
  r := public.receive_inbound_webhook(null, '{"title": "Guess"}');
  assert r = unknown, 'missing token → the same 401';
  r := public.receive_inbound_webhook(upper((select val from ib_vals where name = 't1')), '{"title": "Guess"}');
  assert r = unknown, 'tokens are exact';

  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'),
    '{"title": "  Spring flyer  ", "notes": "From the site", "due_on": "2026-11-02"}');
  assert (r ->> 'ok')::boolean and (r ->> 'status')::integer = 201, format('a valid call creates a task, got %s', r);
  insert into ib_ids values ('task1', (r ->> 'task_id')::uuid);

  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), jsonb_build_object(
    'title', 'Mapped', 'assignee_email', 'IB-Viewer@example.com', 'tags', jsonb_build_array('ib web', 'IB Old', 'Nope'),
    'fields', jsonb_build_object('priority', 'High', 'Budget', 5, 'Launch', '2026-12-01', 'Reviewers', jsonb_build_array('ib-editor@example.com', 'ib-outsider@example.com'), 'Mystery', 1),
    'surprise', true
  )::text);
  assert (r ->> 'status')::integer = 201, format('mapped call, got %s', r);
  insert into ib_ids values ('task2', (r ->> 'task_id')::uuid);
  assert r -> 'warnings' @> '["Ignored unknown key “surprise”"]'::jsonb, format('unknown keys warn, got %s', r -> 'warnings');
  assert r -> 'warnings' @> '["Unknown or archived tag “IB Old” skipped", "Unknown or archived tag “Nope” skipped"]'::jsonb,
    'unknown and archived tags warn';
  assert r -> 'warnings' @> '["Unknown field “Mystery” skipped"]'::jsonb, 'unknown fields warn';
  assert r::text not like '%alhc_in_%', 'the response never carries the token';

  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), jsonb_build_object(
    'title', 'Bad assignee', 'assignee_email', 'ib-outsider@example.com', 'fields', jsonb_build_object('Budget', 'lots')
  )::text);
  assert (r ->> 'status')::integer = 201, 'unmatched references still create the task';
  insert into ib_ids values ('task3', (r ->> 'task_id')::uuid);
  assert r -> 'warnings' @> '["assignee_email isn''t a member of this project; used the default assignee"]'::jsonb,
    format('a non-member assignee warns, got %s', r -> 'warnings');
  assert r::text not like '%lots%', 'warnings never echo values';

  -- Invalid bodies create nothing.
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), '{"notes": "no title"}');
  assert (r ->> 'status')::integer = 422 and r ->> 'error' = 'title is required (a string)', format('title required, got %s', r);
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), '{"title": "x", "due_on": "2026-02-30"}');
  assert (r ->> 'status')::integer = 422, format('impossible dates fail, got %s', r);
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), '{"title": "x", "tags": "IB Web"}');
  assert (r ->> 'status')::integer = 422, 'tags must be an array';
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), '{"title": "x", "tags": null, "fields": null, "notes": null}');
  assert (r ->> 'status')::integer = 201, format('explicit nulls are fine, got %s', r);
  insert into ib_ids values ('task_nulls', (r ->> 'task_id')::uuid);
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), 'not json');
  assert (r ->> 'status')::integer = 400, 'non-JSON → 400';
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), '["title"]');
  assert (r ->> 'status')::integer = 400, 'arrays → 400';
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), jsonb_build_object('title', 'big', 'notes', repeat('x', 70000))::text);
  assert (r ->> 'status')::integer = 413, format('bodies over 64 KB → 413, got %s', r);
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), '{"title": "x"}', null, null, 'bad key with spaces');
  assert (r ->> 'status')::integer = 400, 'odd idempotency keys → 400';

  -- Idempotency-Key: one task.
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), '{"title": "Once"}', null, null, 'order-42');
  assert (r ->> 'status')::integer = 201, 'first keyed call creates';
  insert into ib_ids values ('task_once', (r ->> 'task_id')::uuid);
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), '{"title": "Once again"}', null, null, 'order-42');
  assert (r ->> 'status')::integer = 200 and (r ->> 'duplicate')::boolean
    and (r ->> 'task_id')::uuid = (select id from ib_ids where name = 'task_once'), format('replayed key → same task, got %s', r);
end $$;

reset role;

do $$
declare
  t1 uuid := (select id from ib_ids where name = 'task1');
  t2 uuid := (select id from ib_ids where name = 'task2');
  t3 uuid := (select id from ib_ids where name = 'task3');
  p uuid := (select id from ib_ids where name = 'p');
  admin uuid := (select id from ib_ids where name = 'admin');
  editor uuid := (select id from ib_ids where name = 'editor');
  viewer uuid := (select id from ib_ids where name = 'viewer');
begin
  assert (select title from public.tasks where id = t1) = 'Spring flyer', 'title is trimmed';
  assert (select notes from public.tasks where id = t1) = 'From the site', 'notes are kept as sent';
  assert (select due_on from public.tasks where id = t1) = '2026-11-02', 'due date set';
  assert (select source from public.tasks where id = t1) = 'inbound', 'source is inbound';
  assert (select created_by from public.tasks where id = t1) = admin, 'written as the endpoint creator';
  assert (select home_project_id from public.tasks where id = t1) = p, 'in the endpoint project';
  assert (select section_id from public.task_projects where task_id = t1 and project_id = p) = (select id from ib_ids where name = 'inbox'),
    'lands in the endpoint section';
  assert (select assignee_id from public.tasks where id = t1) = editor, 'default assignee';
  assert exists (select 1 from public.task_tags where task_id = t1 and tag_id = (select id from ib_ids where name = 'urgent') and deleted_at is null),
    'default tags';
  assert (select actor_id from public.task_stories where task_id = t1 and kind = 'created') = admin, 'the created story names the creator';
  assert (select data ->> 'endpoint_name' from public.task_stories where task_id = t1 and kind = 'inbound_received') = 'Website intake',
    'an inbound_received story';
  assert exists (select 1 from public.inbox_items where task_id = t1 and recipient_id = editor and kind = 'assigned'),
    'the assignee is notified';
  assert not exists (select 1 from public.task_followers where task_id = t1 and profile_id = admin and deleted_at is null),
    'the creator doesn''t follow every inbound task';
  assert exists (select 1 from public.task_followers where task_id = t1 and profile_id = editor and deleted_at is null),
    'the assignee follows';

  assert (select assignee_id from public.tasks where id = t2) = viewer, 'assignee_email matches a member (case-insensitive)';
  assert (select count(*) from public.task_tags where task_id = t2 and deleted_at is null) = 2, 'default + payload tags';
  assert (select value from public.task_field_values tv join public.custom_fields cf on cf.id = tv.field_id
          where tv.task_id = t2 and cf.name = 'Priority') = '"hi"'::jsonb, 'single-select by option name';
  assert (select value from public.task_field_values tv join public.custom_fields cf on cf.id = tv.field_id
          where tv.task_id = t2 and cf.name = 'Budget') = '5'::jsonb, 'number';
  assert (select value from public.task_field_values tv join public.custom_fields cf on cf.id = tv.field_id
          where tv.task_id = t2 and cf.name = 'Launch') = '"2026-12-01"'::jsonb, 'date';
  assert (select value from public.task_field_values tv join public.custom_fields cf on cf.id = tv.field_id
          where tv.task_id = t2 and cf.name = 'Reviewers') = jsonb_build_array(editor), 'people by member email only';
  assert (select assignee_id from public.tasks where id = t3) = editor, 'a non-member email falls back to the default';

  assert (select count(*) from public.tasks where home_project_id = p and source = 'inbound') = 5,
    'invalid calls and the duplicate created nothing';
  assert (select count(*) from public.tasks where title = 'Once again') = 0, 'the duplicate body was not used';
  assert (select count(*) from public.inbound_calls where endpoint_id = (select id from ib_ids where name = 'e1') and status = 'created') = 5,
    'five created calls logged';
  assert (select count(*) from public.inbound_calls where endpoint_id = (select id from ib_ids where name = 'e1') and status = 'duplicate') = 1,
    'one duplicate logged';
  assert (select count(*) from public.inbound_calls where endpoint_id = (select id from ib_ids where name = 'e1') and status = 'invalid') = 7,
    'invalid calls logged';
  assert (select current_setting('request.jwt.claim.sub', true)) = '', 'the impersonation setting is restored';
end $$;

-- Disabled, rotated, and deleted tokens create nothing ---------------------------------------------

set role authenticated;
select set_config('request.jwt.claim.sub', 'f6f6f6f6-0000-4000-8000-000000000002', false) is not null as ok \gset
update public.inbound_endpoints set enabled = false where id = (select id from ib_ids where name = 'e1');

set role anon;
select set_config('request.jwt.claim.sub', '', false) is not null as ok \gset
do $$
declare
  r jsonb := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), '{"title": "While disabled"}');
begin
  assert r = '{"ok": false, "error": "Unauthorized", "status": 401}'::jsonb, format('disabled → generic 401, got %s', r);
end $$;

set role authenticated;
select set_config('request.jwt.claim.sub', 'f6f6f6f6-0000-4000-8000-000000000002', false) is not null as ok \gset
update public.inbound_endpoints set enabled = true where id = (select id from ib_ids where name = 'e1');
do $$
declare
  rotated jsonb := public.rotate_inbound_token((select id from ib_ids where name = 'e1'));
begin
  assert rotated ->> 'token' ~ '^alhc_in_[0-9a-f]{64}$' and rotated ->> 'token' <> (select val from ib_vals where name = 't1'),
    format('rotation returns a new token, got %s', rotated);
  insert into ib_vals values ('t1_new', rotated ->> 'token');
end $$;
update public.inbound_endpoints set deleted_at = now() where id = (select id from ib_ids where name = 'e4');
do $$
begin
  begin
    update public.inbound_endpoints set deleted_at = null where id = (select id from ib_ids where name = 'e4');
    raise exception 'deleted endpoints stay deleted';
  exception when check_violation then null;
  end;
end $$;

set role anon;
select set_config('request.jwt.claim.sub', '', false) is not null as ok \gset
do $$
declare
  r jsonb;
begin
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1'), '{"title": "Old token"}');
  assert r = '{"ok": false, "error": "Unauthorized", "status": 401}'::jsonb, 'a rotated-out token → generic 401';
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't4'), '{"title": "Deleted"}');
  assert r = '{"ok": false, "error": "Unauthorized", "status": 401}'::jsonb, 'a deleted endpoint → generic 401';
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1_new'), '{"title": "New token"}');
  assert (r ->> 'status')::integer = 201, format('the new token works, got %s', r);
end $$;

reset role;
do $$
begin
  assert (select count(*) from public.tasks where title in ('While disabled', 'Old token', 'Deleted')) = 0,
    'disabled, rotated, and deleted tokens created nothing';
  assert (select count(*) from public.inbound_calls where endpoint_id = (select id from ib_ids where name = 'e4')) = 0,
    'calls to a deleted endpoint aren''t logged';
end $$;

-- Signatures: missing, bad, stale, replayed --------------------------------------------------------

do $$
declare
  secret text := (select val from ib_vals where name = 's2');
  ts text := extract(epoch from clock_timestamp())::bigint::text;
  stale text := (extract(epoch from clock_timestamp())::bigint - 1000)::text;
  body text := '{"title": "Signed request", "notes": "naïve café"}';
begin
  insert into ib_vals values
    ('ts', ts),
    ('body', body),
    ('sig', 'sha256=' || encode(public.inbound_hmac_sha256(convert_to(secret, 'UTF8'), convert_to(ts || '.' || body, 'UTF8')), 'hex')),
    ('stale_ts', stale),
    ('stale_sig', 'sha256=' || encode(public.inbound_hmac_sha256(convert_to(secret, 'UTF8'), convert_to(stale || '.' || body, 'UTF8')), 'hex')),
    ('wrong_sig', 'sha256=' || encode(public.inbound_hmac_sha256(convert_to('whsec_some_other_secret_0000', 'UTF8'), convert_to(ts || '.' || body, 'UTF8')), 'hex')),
    ('keyed_sig', 'sha256=' || encode(public.inbound_hmac_sha256(convert_to(secret, 'UTF8'), convert_to(ts || '.' || '{"title": "Keyed signed"}', 'UTF8')), 'hex'));
end $$;

set role anon;
select set_config('request.jwt.claim.sub', '', false) is not null as ok \gset
do $$
declare
  t text := (select val from ib_vals where name = 't2');
  body text := (select val from ib_vals where name = 'body');
  ts text := (select val from ib_vals where name = 'ts');
  unauthorized constant jsonb := '{"ok": false, "error": "Unauthorized", "status": 401}';
  r jsonb;
begin
  r := public.receive_inbound_webhook(t, body);
  assert r = unauthorized, format('no signature → generic 401, got %s', r);
  r := public.receive_inbound_webhook(t, body, ts, (select val from ib_vals where name = 'wrong_sig'));
  assert r = unauthorized, 'a wrong key → generic 401';
  r := public.receive_inbound_webhook(t, body || ' ', ts, (select val from ib_vals where name = 'sig'));
  assert r = unauthorized, 'a changed body → generic 401';
  r := public.receive_inbound_webhook(t, body, (select val from ib_vals where name = 'stale_ts'), (select val from ib_vals where name = 'stale_sig'));
  assert r = unauthorized, 'a stale (but correctly signed) timestamp → generic 401';
  r := public.receive_inbound_webhook(t, body, 'yesterday', (select val from ib_vals where name = 'sig'));
  assert r = unauthorized, 'a malformed timestamp → generic 401';

  r := public.receive_inbound_webhook(t, body, ts, upper((select val from ib_vals where name = 'sig')));
  assert (r ->> 'status')::integer = 201, format('a correct signature creates the task (hex case-insensitive), got %s', r);
  r := public.receive_inbound_webhook(t, body, ts, (select val from ib_vals where name = 'sig'));
  assert r = unauthorized, format('a replay → generic 401, got %s', r);

  r := public.receive_inbound_webhook(t, '{"title": "Keyed signed"}', ts, (select val from ib_vals where name = 'keyed_sig'), 'k-1');
  assert (r ->> 'status')::integer = 201, 'keyed signed call';
  r := public.receive_inbound_webhook(t, '{"title": "Keyed signed"}', ts, (select val from ib_vals where name = 'keyed_sig'), 'k-1');
  assert (r ->> 'status')::integer = 200 and (r ->> 'duplicate')::boolean, 'a keyed replay returns the original task';
end $$;

reset role;
do $$
declare
  e2 uuid := (select id from ib_ids where name = 'e2');
begin
  assert (select count(*) from public.tasks where title = 'Signed request') = 1, 'one task despite the replay';
  assert (select notes from public.tasks where title = 'Signed request') = 'naïve café', 'UTF-8 bodies verify and survive';
  assert (select count(*) from public.tasks where title = 'Keyed signed') = 1, 'one keyed signed task';
  assert (select count(*) from public.inbound_calls where endpoint_id = e2 and status = 'rejected') = 6,
    format('six rejections logged, got %s', (select count(*) from public.inbound_calls where endpoint_id = e2 and status = 'rejected'));
  assert exists (select 1 from public.inbound_calls where endpoint_id = e2 and error like 'Stale X-ALHC-Timestamp%'), 'stale reason logged';
  assert exists (select 1 from public.inbound_calls where endpoint_id = e2 and error like 'Replayed request%'), 'replay reason logged';
  assert not exists (
    select 1 from public.inbound_calls
    where coalesce(error, '') ~ '(alhc_in_|whsec_|sha256=)' or warnings::text ~ '(alhc_in_|whsec_|sha256=)'
  ), 'the log never holds tokens, secrets, or signatures';
  assert not exists (
    select 1 from information_schema.columns where table_schema = 'public' and column_name ilike '%signature%'
  ), 'signatures are never stored';
  assert not exists (select 1 from public.inbound_endpoints where token_hash like 'alhc_in_%' or token_hint like 'alhc_in_%'),
    'tokens are stored only as hashes';
end $$;

-- Removing the signing secret, and asking for one later ---------------------------------------------

set role authenticated;
select set_config('request.jwt.claim.sub', 'f6f6f6f6-0000-4000-8000-000000000002', false) is not null as ok \gset
do $$
declare
  r jsonb;
begin
  r := public.set_inbound_signing_secret((select id from ib_ids where name = 'e2'), false);
  assert r ->> 'signing_secret' is null, 'removing returns nothing';
  assert (select signing_secret_set_at from public.inbound_endpoints where id = (select id from ib_ids where name = 'e2')) is null,
    'no signing secret now';
  r := public.set_inbound_signing_secret((select id from ib_ids where name = 'e2'), true);
  assert r ->> 'signing_secret' ~ '^whsec_[0-9a-f]{64}$' and r ->> 'signing_secret' <> (select val from ib_vals where name = 's2'),
    'a new secret is returned once';
end $$;

reset role;
do $$
begin
  assert (select signing_secret from public.inbound_endpoints where id = (select id from ib_ids where name = 'e2'))
    <> (select val from ib_vals where name = 's2'), 'the old secret is retired';
end $$;

-- Rate limit ----------------------------------------------------------------------------------------

set role anon;
select set_config('request.jwt.claim.sub', '', false) is not null as ok \gset
do $$
declare
  t text := (select val from ib_vals where name = 't3');
  r jsonb;
begin
  for i in 1 .. 60 loop
    r := public.receive_inbound_webhook(t, '{"notes": "no title"}');
    assert (r ->> 'status')::integer = 422, format('call %s is processed, got %s', i, r);
  end loop;
  r := public.receive_inbound_webhook(t, '{"title": "One too many"}');
  assert (r ->> 'status')::integer = 429, format('the 61st call in a minute → 429, got %s', r);
  r := public.receive_inbound_webhook(t, '{"title": "Still too many"}');
  assert (r ->> 'status')::integer = 429, 'still limited';
end $$;

reset role;
do $$
begin
  assert (select count(*) from public.tasks where title in ('One too many', 'Still too many')) = 0, 'rate-limited calls create nothing';
  assert (select count(*) from public.inbound_calls where endpoint_id = (select id from ib_ids where name = 'e3') and status = 'rate_limited') = 1,
    'one rate-limited row per minute';
end $$;

-- The creator's access is re-checked: an archived project (everyone capped at Viewer) creates nothing

set role authenticated;
select set_config('request.jwt.claim.sub', 'f6f6f6f6-0000-4000-8000-000000000001', false) is not null as ok \gset
do $$ begin perform public.set_project_archived((select id from ib_ids where name = 'p'), true); end $$;

set role anon;
select set_config('request.jwt.claim.sub', '', false) is not null as ok \gset
do $$
declare
  r jsonb := public.receive_inbound_webhook((select val from ib_vals where name = 't1_new'), '{"title": "While archived"}');
begin
  assert r = '{"ok": false, "error": "Unauthorized", "status": 401}'::jsonb, format('archived → generic 401, got %s', r);
end $$;

set role authenticated;
select set_config('request.jwt.claim.sub', 'f6f6f6f6-0000-4000-8000-000000000001', false) is not null as ok \gset
do $$
begin
  perform public.set_project_archived((select id from ib_ids where name = 'p'), false);
  perform public.update_project_member_role((select id from ib_ids where name = 'p'), (select id from ib_ids where name = 'admin'), 'commenter');
end $$;

set role anon;
select set_config('request.jwt.claim.sub', '', false) is not null as ok \gset
do $$
declare
  r jsonb := public.receive_inbound_webhook((select val from ib_vals where name = 't1_new'), '{"title": "Creator demoted"}');
begin
  assert r = '{"ok": false, "error": "Unauthorized", "status": 401}'::jsonb, format('a creator below Editor → generic 401, got %s', r);
end $$;

set role authenticated;
select set_config('request.jwt.claim.sub', 'f6f6f6f6-0000-4000-8000-000000000001', false) is not null as ok \gset
do $$ begin perform public.update_project_member_role((select id from ib_ids where name = 'p'), (select id from ib_ids where name = 'admin'), 'admin'); end $$;

reset role;
do $$
begin
  assert (select count(*) from public.tasks where title in ('While archived', 'Creator demoted')) = 0, 'nothing created without the creator''s access';
  assert (select count(*) from public.inbound_calls where endpoint_id = (select id from ib_ids where name = 'e1')
          and error like 'The endpoint''s creator can no longer add tasks%') = 2, 'both refusals are logged for the admin';
end $$;

-- Rules: inbound_received { endpoint_id? } and source_is inbound ------------------------------------

set role authenticated;
select set_config('request.jwt.claim.sub', 'f6f6f6f6-0000-4000-8000-000000000002', false) is not null as ok \gset
do $$
declare
  p uuid := (select id from ib_ids where name = 'p');
  other_endpoint uuid;
begin
  insert into public.rules (project_id, name, enabled, trigger_type, trigger_config, actions) values
    (p, 'Website only', true, 'inbound_received', jsonb_build_object('endpoint_id', (select id from ib_ids where name = 'e1')),
     '[{"type": "add_comment", "body": "Thanks from the website rule"}]'),
    (p, 'Any inbound', true, 'inbound_received', '{}', jsonb_build_array(jsonb_build_object('type', 'move_section', 'section_id', (select id from ib_ids where name = 'doing')))),
    (p, 'Inbound source', true, 'task_created', '{}', '[{"type": "add_comment", "body": "Came in from outside"}]');
  update public.rules set conditions = '[{"type": "source_is", "source": "inbound"}]' where name = 'Inbound source' and project_id = p;
  begin
    insert into public.rules (project_id, name, trigger_type, trigger_config, actions) values
      (p, 'Wrong endpoint', 'inbound_received', jsonb_build_object('endpoint_id', gen_random_uuid()), '[{"type": "add_comment", "body": "x"}]');
    raise exception 'an endpoint outside the project should fail';
  exception when check_violation then null;
  end;
  begin
    insert into public.rules (project_id, name, trigger_type, conditions, actions) values
      (p, 'Bad source', 'task_created', '[{"type": "source_is", "source": "smoke-signal"}]', '[{"type": "add_comment", "body": "x"}]');
    raise exception 'unknown sources should fail';
  exception when check_violation then null;
  end;
end $$;

set role anon;
select set_config('request.jwt.claim.sub', '', false) is not null as ok \gset
do $$
declare
  r jsonb;
begin
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't1_new'), '{"title": "Rule check website"}');
  assert (r ->> 'status')::integer = 201, format('rule check, got %s', r);
  insert into ib_ids values ('rule_task1', (r ->> 'task_id')::uuid);
  r := public.receive_inbound_webhook((select val from ib_vals where name = 't2'), '{"title": "Rule check other"}');
  assert (r ->> 'status')::integer = 401, 'the signed endpoint still wants a signature';
end $$;

reset role;
do $$
declare
  t1 uuid := (select id from ib_ids where name = 'rule_task1');
  p uuid := (select id from ib_ids where name = 'p');
begin
  assert exists (select 1 from public.comments where task_id = t1 and body = 'Thanks from the website rule'), 'the endpoint rule fired';
  assert (select section_id from public.task_projects where task_id = t1 and project_id = p) = (select id from ib_ids where name = 'doing'),
    'the any-endpoint rule fired';
end $$;
-- task_created rules fire at commit (deferred), so check them in a later statement.
do $$
declare
  t1 uuid := (select id from ib_ids where name = 'rule_task1');
begin
  assert exists (select 1 from public.comments where task_id = t1 and body = 'Came in from outside'), 'source_is inbound matches';
  assert not exists (select 1 from public.comments where task_id = (select id from ib_ids where name = 'task1') and body = 'Came in from outside'),
    'rules don''t run for earlier tasks';
end $$;

-- The endpoint filter: a task created through another endpoint doesn't fire the website-only rule.
do $$
declare
  secret text := (select signing_secret from public.inbound_endpoints where id = (select id from ib_ids where name = 'e2'));
  ts text := extract(epoch from clock_timestamp())::bigint::text;
  body text := '{"title": "Rule check signed"}';
begin
  insert into ib_vals values ('rule_ts', ts),
    ('rule_sig', 'sha256=' || encode(public.inbound_hmac_sha256(convert_to(secret, 'UTF8'), convert_to(ts || '.' || body, 'UTF8')), 'hex'));
end $$;
set role anon;
select set_config('request.jwt.claim.sub', '', false) is not null as ok \gset
do $$
declare
  r jsonb := public.receive_inbound_webhook((select val from ib_vals where name = 't2'), '{"title": "Rule check signed"}',
    (select val from ib_vals where name = 'rule_ts'), (select val from ib_vals where name = 'rule_sig'));
begin
  assert (r ->> 'status')::integer = 201, format('signed rule check, got %s', r);
  insert into ib_ids values ('rule_task2', (r ->> 'task_id')::uuid);
end $$;
reset role;
do $$
declare
  t2 uuid := (select id from ib_ids where name = 'rule_task2');
begin
  assert not exists (select 1 from public.comments where task_id = t2 and body = 'Thanks from the website rule'), 'the endpoint filter holds';
  assert (select section_id from public.task_projects where task_id = t2 and project_id = (select id from ib_ids where name = 'p'))
    = (select id from ib_ids where name = 'doing'), 'the any-endpoint rule fires for every endpoint';
end $$;

-- Imports and copies still never fire rules -----------------------------------------------------------

do $$
declare
  def text := pg_get_functiondef('public.fire_rules(text, uuid, uuid, jsonb)'::regprocedure);
  runs integer := (select count(*) from public.rule_runs);
begin
  assert def like '%if public.import_context_id() is not null then%' and def like '%if public.copy_context_id() is not null then%',
    'fire_rules keeps its import and copy checks';
  perform set_config('alhc.import_run_id', gen_random_uuid()::text, true);
  perform public.fire_rules('inbound_received', (select id from ib_ids where name = 'task1'), (select id from ib_ids where name = 'p'),
    jsonb_build_object('endpoint_id', (select id from ib_ids where name = 'e1')));
  assert (select count(*) from public.rule_runs) = runs, 'nothing fires during an import';
  perform set_config('alhc.import_run_id', '', true);
  perform set_config('alhc.copy_id', gen_random_uuid()::text, true);
  perform public.fire_rules('inbound_received', (select id from ib_ids where name = 'task1'), (select id from ib_ids where name = 'p'),
    jsonb_build_object('endpoint_id', (select id from ib_ids where name = 'e1')));
  assert (select count(*) from public.rule_runs) = runs, 'nothing fires during a copy';
  perform set_config('alhc.copy_id', '', true);
  assert pg_get_functiondef('public.notify_with(uuid, uuid, text, uuid, jsonb)'::regprocedure) like '%import_context_id()%copy_context_id()%',
    'notify_with keeps its checks';
  assert pg_get_functiondef('public.add_story(uuid, text, jsonb)'::regprocedure) like '%import_context_id()%',
    'add_story keeps its checks';
end $$;

-- Copies never carry endpoints ------------------------------------------------------------------------

do $$
declare
  snap jsonb := public.project_snapshot((select id from ib_ids where name = 'p'), '{"rules": true}'::jsonb);
begin
  assert snap::text not like '%alhc_in_%' and snap::text not like '%whsec_%' and snap::text not like '%token_hash%',
    'snapshots carry no endpoint tokens or secrets';
end $$;

-- The log: Admin+ read it, nobody writes it -----------------------------------------------------------

set role authenticated;
select set_config('request.jwt.claim.sub', 'f6f6f6f6-0000-4000-8000-000000000002', false) is not null as ok \gset
do $$
begin
  assert (select count(*) from public.inbound_calls) > 0, 'admins read the log';
  begin
    perform replay_digest from public.inbound_calls limit 1;
    raise exception 'replay digests are internal';
  exception when insufficient_privilege then null;
  end;
  begin
    insert into public.inbound_calls (endpoint_id, project_id, status, http_status)
    values ((select id from ib_ids where name = 'e1'), (select id from ib_ids where name = 'p'), 'created', 201);
    raise exception 'nobody writes the log';
  exception when insufficient_privilege then null;
  end;
  begin
    perform public.log_inbound_call(null::public.inbound_endpoints, 'created', 201);
    raise exception 'the log helper is internal';
  exception when insufficient_privilege then null;
  end;
end $$;

-- EXECUTE surface: anon gets exactly the public form RPCs and the receiver ---------------------------

reset role;
do $$
declare
  exposed text;
begin
  select string_agg(p.proname, ',' order by p.proname) into exposed
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prosecdef and has_function_privilege('anon', p.oid, 'execute');
  assert exposed = 'get_public_form,receive_inbound_webhook,submit_form', format('anon SECURITY DEFINER surface: %s', exposed);

  assert not has_function_privilege('anon', 'public.create_inbound_endpoint(uuid, text, uuid, uuid, uuid[], boolean)', 'execute')
    and not has_function_privilege('anon', 'public.rotate_inbound_token(uuid)', 'execute')
    and not has_function_privilege('anon', 'public.set_inbound_signing_secret(uuid, boolean)', 'execute'),
    'anon manages nothing';
  assert not has_function_privilege('authenticated', 'public.inbound_hmac_sha256(bytea, bytea)', 'execute')
    and not has_function_privilege('anon', 'public.inbound_hmac_sha256(bytea, bytea)', 'execute'), 'HMAC is internal';
  assert not has_function_privilege('authenticated', 'public.log_inbound_call(public.inbound_endpoints, text, integer, text, uuid, jsonb, text, text)', 'execute'),
    'the log helper is internal';
  assert not has_table_privilege('anon', 'public.inbound_endpoints', 'select')
    and not has_table_privilege('anon', 'public.inbound_endpoints', 'insert')
    and not has_table_privilege('anon', 'public.inbound_calls', 'select'), 'anon has no table grants';
  assert not has_column_privilege('authenticated', 'public.inbound_endpoints', 'token_hash', 'select')
    and not has_column_privilege('authenticated', 'public.inbound_endpoints', 'signing_secret', 'select')
    and not has_column_privilege('authenticated', 'public.inbound_endpoints', 'token_hash', 'update')
    and not has_column_privilege('authenticated', 'public.inbound_endpoints', 'signing_secret', 'insert'),
    'no client reads or writes hashes and secrets';
  assert not exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.prosecdef and p.proname in (
      'create_inbound_endpoint', 'rotate_inbound_token', 'set_inbound_signing_secret', 'guard_inbound_endpoint', 'log_inbound_call'
    )
  ), 'endpoint management is SECURITY INVOKER';
  -- Since Email live the helper stays (AGENTS.md → Conventions); it must stay internal.
  assert not exists (
    select 1 from pg_proc where proname = 'alhc_patch_function'
      and (has_function_privilege('authenticated', oid, 'execute') or has_function_privilege('anon', oid, 'execute'))
  ), 'the patch helper is internal';
end $$;

select 'inbound integrations smoke: all assertions passed' as result;
