"use client";

import Link from "next/link";
import { useState } from "react";
import { CheckCircle2, Copy, Inbox, KeyRound, RotateCcw, ShieldCheck, Trash2, XCircle } from "lucide-react";
import { Timestamp } from "@/components/timestamp";
import { useServerAction } from "@/components/toast";
import { EmptyState } from "@/components/ui";
import {
  createInboundEndpoint,
  deleteInboundEndpoint,
  rotateInboundToken,
  setInboundSigningSecret,
  updateInboundEndpoint,
} from "@/lib/actions";
import {
  INBOUND_CALL_STATUS_LABELS,
  INBOUND_RATE_PER_MINUTE,
  INBOUND_TIMESTAMP_TOLERANCE_SECONDS,
  inboundCurlExample,
  inboundUrl,
  type InboundCall,
  type InboundCallStatus,
  type InboundEndpoint,
  type RevealedInboundCredentials,
} from "@/lib/inbound-shared";
import { SIGNATURE_HEADER, TIMESTAMP_HEADER } from "@/lib/integrations-shared";

type Option = { id: string; name: string };
type TagOption = Option & { archived: boolean };

const inputClass =
  "rounded-md border border-zinc-200 bg-white px-2 py-1.5 text-sm focus:border-accent-500 focus:outline-none disabled:opacity-50";
const buttonClass =
  "inline-flex shrink-0 items-center gap-1.5 rounded-md border border-zinc-300 px-2.5 py-1 text-sm text-zinc-700 hover:border-accent-500 hover:text-accent-700 disabled:opacity-50";

const CALL_STYLE: Record<InboundCallStatus, string> = {
  created: "bg-green-50 text-green-800",
  duplicate: "bg-zinc-100 text-zinc-600",
  rejected: "bg-red-50 text-red-700",
  invalid: "bg-amber-50 text-amber-800",
  rate_limited: "bg-amber-50 text-amber-800",
  failed: "bg-red-50 text-red-700",
};

// Settings → Inbound (Admin+): endpoints that create tasks in this project from outside. Tokens and
// signing secrets are generated by the database and shown once, right after they are created; the list
// only ever shows a hint (last 4 characters) and whether requests must be signed.
export function InboundSettings({
  projectId,
  origin,
  endpoints,
  calls,
  sections,
  members,
  tags,
}: {
  projectId: string;
  origin: string;
  endpoints: InboundEndpoint[];
  calls: InboundCall[];
  sections: Option[];
  members: Option[];
  tags: TagOption[];
}) {
  const [revealed, setRevealed] = useState<RevealedInboundCredentials | null>(null);
  const names = new Map(endpoints.map((e) => [e.id, e.name]));

  return (
    <div className="mx-auto max-w-3xl space-y-6 px-gutter py-5">
      <section className="rounded-lg border border-zinc-200" aria-labelledby="inbound-heading">
        <div className="border-b border-zinc-200 px-5 py-4">
          <h2 id="inbound-heading" className="text-sm font-semibold text-zinc-900">
            Inbound webhooks
          </h2>
          <p className="mt-1 text-sm text-zinc-600">
            Let another tool (Zapier, a website form, a script) create tasks in this project by POSTing JSON to a
            private URL. Tasks are created as the person who made the endpoint, land in its section with its default
            assignee and tags, and fire this project’s rules (use the{" "}
            <span className="font-medium text-zinc-900">Created by inbound webhook</span> trigger). The URL contains
            a secret token that is shown once; anyone with it can create tasks here, so treat it like a password.
          </p>
        </div>

        {revealed ? (
          <RevealPanel
            origin={origin}
            name={names.get(revealed.endpointId) ?? "the endpoint"}
            revealed={revealed}
            onDone={() => setRevealed(null)}
          />
        ) : null}

        {endpoints.length === 0 ? (
          <EmptyState icon={Inbox} title="No inbound webhooks yet" size="inline">
            Add one below, then point your tool at the URL it shows you.
          </EmptyState>
        ) : (
          <ul className="divide-y divide-zinc-100">
            {endpoints.map((e) => (
              <EndpointRow
                key={e.id}
                endpoint={e}
                sections={sections}
                members={members}
                tags={tags}
                onReveal={setRevealed}
              />
            ))}
          </ul>
        )}

        <NewEndpoint projectId={projectId} sections={sections} members={members} tags={tags} onCreated={setRevealed} />
      </section>

      <CallLog projectId={projectId} calls={calls} names={names} />

      <PayloadReference />
    </div>
  );
}

function CopyButton({ value, label }: { value: string; label: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      type="button"
      aria-label={`Copy ${label}`}
      onClick={() => {
        void navigator.clipboard?.writeText(value).then(() => setCopied(true));
      }}
      className={buttonClass}
    >
      <Copy className="size-3.5" aria-hidden />
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

function RevealPanel({
  origin,
  name,
  revealed,
  onDone,
}: {
  origin: string;
  name: string;
  revealed: RevealedInboundCredentials;
  onDone: () => void;
}) {
  const url = revealed.token ? inboundUrl(origin, revealed.token) : null;
  return (
    <div role="status" className="space-y-3 border-b border-amber-200 bg-amber-50 px-5 py-4">
      <p className="text-sm font-medium text-amber-900">
        Copy {revealed.token && revealed.signingSecret ? "these now" : "this now"} — for “{name}” it won’t be shown
        again.
      </p>
      {url ? (
        <div className="space-y-1">
          <p className="text-xs font-medium text-zinc-700">Endpoint URL</p>
          <div className="flex flex-wrap items-center gap-2">
            <code className="min-w-0 flex-1 break-all rounded bg-white px-2 py-1 font-mono text-xs text-zinc-800">{url}</code>
            <CopyButton value={url} label="endpoint URL" />
          </div>
        </div>
      ) : null}
      {revealed.signingSecret ? (
        <div className="space-y-1">
          <p className="text-xs font-medium text-zinc-700">Signing secret</p>
          <div className="flex flex-wrap items-center gap-2">
            <code className="min-w-0 flex-1 break-all rounded bg-white px-2 py-1 font-mono text-xs text-zinc-800">
              {revealed.signingSecret}
            </code>
            <CopyButton value={revealed.signingSecret} label="signing secret" />
          </div>
          <p className="text-xs text-zinc-600">
            Every request must now carry {TIMESTAMP_HEADER} and {SIGNATURE_HEADER} (see “Request format” below).
          </p>
        </div>
      ) : null}
      {url ? (
        <details className="text-xs text-zinc-700">
          <summary className="cursor-pointer">Example request</summary>
          <pre className="mt-2 overflow-x-auto rounded bg-white p-2 font-mono text-xs text-zinc-800">{inboundCurlExample(url)}</pre>
        </details>
      ) : null}
      <button type="button" onClick={onDone} className={buttonClass}>
        I’ve copied it
      </button>
    </div>
  );
}

function EndpointFields({
  idPrefix,
  sections,
  members,
  tags,
  value,
  onChange,
}: {
  idPrefix: string;
  sections: Option[];
  members: Option[];
  tags: TagOption[];
  value: { name: string; sectionId: string | null; assigneeId: string | null; tagIds: string[] };
  onChange: (next: { name: string; sectionId: string | null; assigneeId: string | null; tagIds: string[] }) => void;
}) {
  const shownTags = tags.filter((t) => !t.archived || value.tagIds.includes(t.id));
  return (
    <div className="grid gap-3 sm:grid-cols-2">
      <label className="flex flex-col gap-1 text-xs font-medium text-zinc-600" htmlFor={`${idPrefix}-name`}>
        Name
        <input
          id={`${idPrefix}-name`}
          required
          maxLength={100}
          value={value.name}
          placeholder="Website intake"
          onChange={(e) => onChange({ ...value, name: e.currentTarget.value })}
          className={inputClass}
        />
      </label>
      <label className="flex flex-col gap-1 text-xs font-medium text-zinc-600" htmlFor={`${idPrefix}-section`}>
        Section
        <select
          id={`${idPrefix}-section`}
          value={value.sectionId ?? ""}
          onChange={(e) => onChange({ ...value, sectionId: e.currentTarget.value || null })}
          className={inputClass}
        >
          <option value="">No section</option>
          {sections.map((s) => (
            <option key={s.id} value={s.id}>
              {s.name}
            </option>
          ))}
        </select>
      </label>
      <label className="flex flex-col gap-1 text-xs font-medium text-zinc-600" htmlFor={`${idPrefix}-assignee`}>
        Default assignee
        <select
          id={`${idPrefix}-assignee`}
          value={value.assigneeId ?? ""}
          onChange={(e) => onChange({ ...value, assigneeId: e.currentTarget.value || null })}
          className={inputClass}
        >
          <option value="">Unassigned</option>
          {members.map((m) => (
            <option key={m.id} value={m.id}>
              {m.name}
            </option>
          ))}
        </select>
      </label>
      <fieldset className="flex flex-col gap-1">
        <legend className="text-xs font-medium text-zinc-600">Default tags</legend>
        {shownTags.length === 0 ? (
          <p className="text-xs text-zinc-500">
            No tags yet — create them in{" "}
            <Link href="/settings/workspace" className="text-accent-700 hover:underline">
              Settings → Workspace
            </Link>
            .
          </p>
        ) : (
          <div className="flex max-h-28 flex-wrap gap-x-3 gap-y-1 overflow-y-auto">
            {shownTags.map((t) => (
              <label key={t.id} className="inline-flex items-center gap-1.5 text-sm text-zinc-700">
                <input
                  type="checkbox"
                  checked={value.tagIds.includes(t.id)}
                  disabled={t.archived && !value.tagIds.includes(t.id)}
                  onChange={(e) =>
                    onChange({
                      ...value,
                      tagIds: e.currentTarget.checked ? [...value.tagIds, t.id] : value.tagIds.filter((x) => x !== t.id),
                    })
                  }
                />
                {t.name}
                {t.archived ? <span className="text-xs text-zinc-500">(archived)</span> : null}
              </label>
            ))}
          </div>
        )}
      </fieldset>
    </div>
  );
}

function NewEndpoint({
  projectId,
  sections,
  members,
  tags,
  onCreated,
}: {
  projectId: string;
  sections: Option[];
  members: Option[];
  tags: TagOption[];
  onCreated: (revealed: RevealedInboundCredentials) => void;
}) {
  const [pending, run] = useServerAction();
  const [open, setOpen] = useState(false);
  const [signed, setSigned] = useState(true);
  const [value, setValue] = useState({ name: "", sectionId: null as string | null, assigneeId: null as string | null, tagIds: [] as string[] });

  if (!open) {
    return (
      <div className="border-t border-zinc-200 px-5 py-3">
        <button type="button" onClick={() => setOpen(true)} className="btn-secondary">
          Add inbound webhook
        </button>
      </div>
    );
  }

  return (
    <form
      className="space-y-3 border-t border-zinc-200 px-5 py-4"
      aria-label="New inbound webhook"
      onSubmit={(e) => {
        e.preventDefault();
        run(async () => {
          const result = await createInboundEndpoint(projectId, { ...value, signed });
          if (!result.error && result.endpointId) {
            onCreated({ endpointId: result.endpointId, token: result.token, signingSecret: result.signingSecret });
            setOpen(false);
            setValue({ name: "", sectionId: null, assigneeId: null, tagIds: [] });
          }
          return result;
        });
      }}
    >
      <EndpointFields idPrefix="new-inbound" sections={sections} members={members} tags={tags} value={value} onChange={setValue} />
      <label className="flex items-start gap-2 text-sm text-zinc-700">
        <input type="checkbox" className="mt-1" checked={signed} onChange={(e) => setSigned(e.currentTarget.checked)} />
        <span>
          Require signed requests (recommended when the sender can compute an HMAC; Zapier’s plain webhooks can’t —
          leave this off for them)
        </span>
      </label>
      <div className="flex gap-2">
        <button type="submit" disabled={pending || !value.name.trim()} className="btn-primary">
          Create
        </button>
        <button type="button" onClick={() => setOpen(false)} className="btn-ghost">
          Cancel
        </button>
      </div>
    </form>
  );
}

function EndpointRow({
  endpoint: e,
  sections,
  members,
  tags,
  onReveal,
}: {
  endpoint: InboundEndpoint;
  sections: Option[];
  members: Option[];
  tags: TagOption[];
  onReveal: (revealed: RevealedInboundCredentials) => void;
}) {
  const [pending, run] = useServerAction();
  const [editing, setEditing] = useState(false);
  const [value, setValue] = useState({ name: e.name, sectionId: e.sectionId, assigneeId: e.assigneeId, tagIds: e.tagIds });
  const section = sections.find((s) => s.id === e.sectionId)?.name ?? "No section";
  const assignee = members.find((m) => m.id === e.assigneeId)?.name ?? "Unassigned";
  const tagNames = e.tagIds.map((id) => tags.find((t) => t.id === id)?.name).filter(Boolean);

  if (editing) {
    return (
      <li className="px-5 py-4">
        <form
          className="space-y-3"
          aria-label={`Edit ${e.name}`}
          onSubmit={(ev) => {
            ev.preventDefault();
            run(async () => {
              const result = await updateInboundEndpoint(e.id, value);
              if (!result.error) setEditing(false);
              return result;
            });
          }}
        >
          <EndpointFields idPrefix={`inbound-${e.id}`} sections={sections} members={members} tags={tags} value={value} onChange={setValue} />
          <div className="flex gap-2">
            <button type="submit" disabled={pending || !value.name.trim()} className="btn-primary">
              Save
            </button>
            <button type="button" onClick={() => setEditing(false)} className="btn-ghost">
              Cancel
            </button>
          </div>
        </form>
      </li>
    );
  }

  return (
    <li className="flex flex-col gap-2 px-5 py-3">
      <div className="flex flex-wrap items-center gap-2 text-sm">
        <span className="font-medium text-zinc-900">{e.name}</span>
        <span
          className={`rounded px-1.5 py-0.5 text-xs font-medium ${e.enabled ? "bg-green-50 text-green-800" : "bg-zinc-100 text-zinc-600"}`}
        >
          {e.enabled ? "On" : "Off"}
        </span>
        <span className="rounded bg-zinc-100 px-1.5 py-0.5 font-mono text-xs text-zinc-700" title="The token's last 4 characters">
          /api/inbound/{e.tokenHint}
        </span>
        {e.signed ? (
          <span className="inline-flex items-center gap-1 text-xs text-zinc-600">
            <ShieldCheck className="size-3.5" aria-hidden />
            Signed requests only
          </span>
        ) : (
          <span className="text-xs text-zinc-500">Token only</span>
        )}
      </div>
      <p className="text-xs text-zinc-500">
        {section} · {assignee}
        {tagNames.length ? ` · tags ${tagNames.join(", ")}` : ""} · token from <Timestamp iso={e.tokenRotatedAt} />
        {e.lastCallAt ? (
          <>
            {" "}
            · last call <Timestamp iso={e.lastCallAt} />
          </>
        ) : (
          " · never called"
        )}
      </p>
      <div className="flex flex-wrap gap-2">
        <button type="button" disabled={pending} onClick={() => setEditing(true)} className={buttonClass}>
          Edit
        </button>
        <button
          type="button"
          disabled={pending}
          onClick={() => run(() => updateInboundEndpoint(e.id, { enabled: !e.enabled }))}
          className={buttonClass}
        >
          {e.enabled ? "Turn off" : "Turn on"}
        </button>
        <button
          type="button"
          disabled={pending}
          aria-label={`Rotate the token of ${e.name}`}
          onClick={() => {
            if (!window.confirm(`Rotate the token of “${e.name}”? The current URL stops working right away.`)) return;
            run(async () => {
              const result = await rotateInboundToken(e.id);
              if (!result.error && result.token) onReveal({ endpointId: e.id, token: result.token });
              return result;
            });
          }}
          className={buttonClass}
        >
          <RotateCcw className="size-3.5" aria-hidden />
          Rotate token
        </button>
        <button
          type="button"
          disabled={pending}
          aria-label={`${e.signed ? "Replace" : "Add"} the signing secret of ${e.name}`}
          onClick={() => {
            if (e.signed && !window.confirm(`Replace the signing secret of “${e.name}”? The old one stops working right away.`)) return;
            run(async () => {
              const result = await setInboundSigningSecret(e.id, true);
              if (!result.error && result.signingSecret) onReveal({ endpointId: e.id, signingSecret: result.signingSecret });
              return result;
            });
          }}
          className={buttonClass}
        >
          <KeyRound className="size-3.5" aria-hidden />
          {e.signed ? "Replace signing secret" : "Require signatures"}
        </button>
        {e.signed ? (
          <button
            type="button"
            disabled={pending}
            onClick={() => {
              if (!window.confirm(`Stop requiring signatures for “${e.name}”? The token alone will be enough.`)) return;
              run(() => setInboundSigningSecret(e.id, false));
            }}
            className={buttonClass}
          >
            Stop requiring signatures
          </button>
        ) : null}
        <button
          type="button"
          disabled={pending}
          aria-label={`Delete ${e.name}`}
          onClick={() => {
            if (!window.confirm(`Delete “${e.name}”? Its URL stops working; tasks it created stay.`)) return;
            run(() => deleteInboundEndpoint(e.id));
          }}
          className={`${buttonClass} hover:border-red-500 hover:text-red-700`}
        >
          <Trash2 className="size-3.5" aria-hidden />
          Delete
        </button>
      </div>
    </li>
  );
}

function CallLog({ projectId, calls, names }: { projectId: string; calls: InboundCall[]; names: Map<string, string> }) {
  const [problemsOnly, setProblemsOnly] = useState(false);
  const shown = calls.filter((c) => !problemsOnly || (c.status !== "created" && c.status !== "duplicate"));

  return (
    <section className="rounded-lg border border-zinc-200" aria-labelledby="inbound-log-heading">
      <div className="border-b border-zinc-200 px-5 py-4">
        <h2 id="inbound-log-heading" className="text-sm font-semibold text-zinc-900">
          Recent calls
        </h2>
        <p className="mt-1 text-sm text-zinc-600">
          The latest 100 calls that reached an endpoint, newest first. Bodies, tokens, and signatures are never stored.
          Calls with an unknown, turned-off, or deleted token aren’t listed: they all get the same “Unauthorized”
          answer, so nobody can tell whether a token exists.
        </p>
        {calls.length > 0 ? (
          <label className="mt-3 inline-flex items-center gap-2 text-sm text-zinc-700">
            <input type="checkbox" checked={problemsOnly} onChange={(e) => setProblemsOnly(e.currentTarget.checked)} />
            Problems only
          </label>
        ) : null}
      </div>
      {calls.length === 0 ? (
        <EmptyState title="No calls yet" size="inline">
          Each call to one of this project’s inbound webhooks shows up here with its result.
        </EmptyState>
      ) : shown.length === 0 ? (
        <EmptyState title="No problems" size="inline">
          Every recent call created a task (or repeated one).
        </EmptyState>
      ) : (
        <ul className="divide-y divide-zinc-100">
          {shown.map((c) => {
            const ok = c.status === "created" || c.status === "duplicate";
            const Icon = ok ? CheckCircle2 : XCircle;
            return (
              <li key={c.id} className="space-y-1 px-5 py-3">
                <div className="flex flex-wrap items-center gap-2 text-sm">
                  <span className={`inline-flex items-center gap-1 rounded px-1.5 py-0.5 text-xs font-medium ${CALL_STYLE[c.status]}`}>
                    <Icon className="size-3.5" aria-hidden />
                    {INBOUND_CALL_STATUS_LABELS[c.status]}
                  </span>
                  <span className="font-medium text-zinc-900">{names.get(c.endpointId) ?? "A deleted endpoint"}</span>
                  <span className="text-xs text-zinc-500">
                    HTTP {c.httpStatus} · <Timestamp iso={c.createdAt} />
                    {c.idempotencyKey ? ` · key ${c.idempotencyKey}` : ""}
                  </span>
                </div>
                {c.taskId ? (
                  <p className="text-xs text-zinc-500">
                    {c.taskTitle ? (
                      <Link href={`/projects/${projectId}?task=${c.taskId}`} className="text-accent-700 hover:underline">
                        {c.taskTitle}
                      </Link>
                    ) : (
                      "A task you can’t open (or deleted)"
                    )}
                  </p>
                ) : null}
                {c.error ? <p className="break-words text-xs text-red-700">{c.error}</p> : null}
                {c.warnings.length ? (
                  <ul className="list-disc pl-5 text-xs text-amber-800">
                    {c.warnings.map((w, i) => (
                      <li key={i}>{w}</li>
                    ))}
                  </ul>
                ) : null}
              </li>
            );
          })}
        </ul>
      )}
    </section>
  );
}

function PayloadReference() {
  return (
    <section className="rounded-lg border border-zinc-200 p-5 text-sm text-zinc-600" aria-labelledby="inbound-format-heading">
      <h2 id="inbound-format-heading" className="text-sm font-semibold text-zinc-900">
        Request format
      </h2>
      <p className="mt-1">
        <code className="font-mono text-xs">POST</code> a JSON object (UTF-8, up to 64 KB) with{" "}
        <code className="font-mono text-xs">Content-Type: application/json</code>:
      </p>
      <ul className="mt-2 list-disc space-y-1 pl-5">
        <li>
          <code className="font-mono text-xs">title</code> (required), <code className="font-mono text-xs">notes</code>,{" "}
          <code className="font-mono text-xs">due_on</code> (YYYY-MM-DD)
        </li>
        <li>
          <code className="font-mono text-xs">assignee_email</code> — a member of this project; otherwise the default
          assignee
        </li>
        <li>
          <code className="font-mono text-xs">tags</code> — tag names, added to the default tags (unknown names are
          skipped)
        </li>
        <li>
          <code className="font-mono text-xs">fields</code> — custom field values by field name: text, number, date,
          true/false, an option name (or a list for multi-select), member emails for people fields, a section name for
          a Status field bound to sections
        </li>
      </ul>
      <p className="mt-2">
        Send an <code className="font-mono text-xs">Idempotency-Key</code> header to make retries safe: the same key
        returns the task it created the first time. Each endpoint takes up to {INBOUND_RATE_PER_MINUTE} calls a
        minute. Answers: 201 created, 200 repeated key, 400 / 413 / 422 bad request (with the reason), 401
        unauthorized, 429 too many requests.
      </p>
      <p className="mt-2">
        Signed endpoints also need <code className="font-mono text-xs">{TIMESTAMP_HEADER}</code> (Unix seconds,
        within {INBOUND_TIMESTAMP_TOLERANCE_SECONDS} seconds of now) and{" "}
        <code className="font-mono text-xs">{SIGNATURE_HEADER}: sha256=&lt;hex HMAC-SHA256(secret, &quot;timestamp.body&quot;)&gt;</code>{" "}
        over the exact body bytes — the same scheme outbound webhooks use. A signature can be used once.
      </p>
    </section>
  );
}
